(function(){
'use strict';
const META={1:['🌱','Baseline & Study System','Lessons 1 & 2'],2:['🗣️','Speaking Baseline & Present Time','Lessons 3 & 4'],3:['⏰','Present Time & Routines','Lessons 5 & 6'],4:['🕰️','Past Time & Experiences','Lessons 7 & 8'],5:['🎉','Special Occasions & Month 1 Check','Lessons 9 & 10'],6:['🚀','Month 1 Consolidation','Lessons 11 & 12']};
let lesson=+(localStorage.getItem('ielts-hao-lesson')||1),major='overview',sub=null,data=null;
const $=s=>document.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’‘]/g,"'").replace(/[^a-z0-9'./-]+/g,' ').trim();
function answers(){const l=(window.IELTS_LESSONS||[]).find(x=>x.id===lesson),m={};(l?.tasks||[]).forEach(t=>m[t.id]=t.answer);m['l1-nationalities']='<p><b>1 Japanese · 2 Chinese · 3 Egyptian · 4 Emirati · 5 Portuguese · 6 Malaysian.</b></p>';return m}
function answer(id){return answers()[id]||'<p>Open response. Compare your work with the task requirements and teacher feedback.</p>'}
function plain(id){const d=document.createElement('div');d.innerHTML=answer(id);return norm(d.textContent)}
function key(el,task){const i=$$('input,textarea,select',task).indexOf(el);return `ielts-hao-v7-${lesson}-${task.dataset.taskId}-${i}`}
function save(el,task){try{localStorage.setItem(key(el,task),el.type==='checkbox'?(el.checked?'1':'0'):el.value)}catch(e){} progress()}
function restore(task){$$('input,textarea,select',task).forEach(el=>{try{const v=localStorage.getItem(key(el,task));if(v!=null){if(el.type==='checkbox')el.checked=v==='1';else el.value=v}}catch(e){};el.addEventListener(el.type==='checkbox'?'change':'input',()=>save(el,task));if(el.tagName==='TEXTAREA')words(el)})}
function words(ta){const w=ta.value.trim()?ta.value.trim().split(/\s+/).length:0,el=ta.parentElement.querySelector('.wordcount');if(el)el.textContent=`${w} word${w===1?'':'s'}`}
function nav(){const b=$('#lessonNav');b.innerHTML='';Object.entries(META).forEach(([id,m])=>{const x=document.createElement('button');x.className='lesson-tab'+(+id===lesson?' on':'');x.innerHTML=`<span class="lnum">${id}</span><span><b>${m[0]} ${m[1]}</b><small>${m[2]}</small></span>`;x.onclick=()=>load(+id);b.appendChild(x)})}
function tabs(){const b=$('#majorTabs');b.innerHTML='';data.major.forEach(m=>{const x=document.createElement('button');x.className='tab'+(m.id===major?' on':'');x.textContent=m.label;x.onclick=()=>{major=m.id;sub=null;render()};b.appendChild(x)})}
function render(){tabs();const m=data.major.find(x=>x.id===major)||data.major[0],sb=$('#subTabs');sb.innerHTML='';let h='';if(m.subtabs?.length){if(!sub||!m.subtabs.some(x=>x.id===sub))sub=m.subtabs[0].id;m.subtabs.forEach(s=>{const x=document.createElement('button');x.className='subtab'+(s.id===sub?' on':'');x.textContent=s.label;x.onclick=()=>{sub=s.id;render()};sb.appendChild(x)});const s=m.subtabs.find(x=>x.id===sub);$('#sectionTitle').textContent=s.title||m.title||m.label;h=s.html||''}else{$('#sectionTitle').textContent=m.title||m.label;h=m.html||''}$('#content').innerHTML=h||'<div class="card">No content in this section.</div>';$('#contentShell').hidden=false;$('#loading').hidden=true;wire();window.scrollTo({top:document.querySelector('main').offsetTop-55,behavior:'smooth'})}
function load(id){lesson=id;major='overview';sub=null;try{localStorage.setItem('ielts-hao-lesson',id)}catch(e){};data=window.IELTS_PRECOMPILED?.[id];nav();const m=META[id];$('#heroIcon').textContent=m[0];$('#title').textContent=`Lesson ${id} · ${m[1]}`;$('#eyebrow').textContent=`Foundation 1 · ${m[2]} · Interactive v7`;$('#outcome').textContent='Full worksheet content rebuilt as direct interactive web practice.';if(!data){$('#loading').hidden=false;$('#loading').textContent='Interactive lesson data is missing. Please refresh once.';$('#contentShell').hidden=true;return}render();progress()}
function check(task){const id=task.dataset.taskId,a=plain(id),score=task.querySelector('.score');let done=0,good=0;$$('.gap',task).forEach(el=>{el.classList.remove('ok','no');const v=norm(el.value);if(!v)return;done++;if(a.includes(v)&&v.length>1){el.classList.add('ok');good++}else el.classList.add('no')});$$('textarea',task).forEach(el=>{if(el.value.trim()){done++;good++}});$$('input[type=checkbox]',task).forEach(el=>{if(el.checked){done++;good++}});if(score)score.textContent=done?`${good}/${done} responses checked`:'Complete the task first.';progress()}
function reset(task){if(!confirm('Reset this task?'))return;$$('input,textarea,select',task).forEach(el=>{try{localStorage.removeItem(key(el,task))}catch(e){};if(el.type==='checkbox')el.checked=false;else el.value='';el.classList.remove('ok','no')});const a=task.querySelector('.ansbox');if(a)a.hidden=true;const s=task.querySelector('.score');if(s)s.textContent='';$$('textarea',task).forEach(words);progress()}
function record(task){$$('.record-btn',task).forEach(btn=>{let rec,chunks=[],timer,start;btn.onclick=async()=>{if(rec?.state==='recording'){rec.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});rec=new MediaRecorder(stream);chunks=[];rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=()=>{stream.getTracks().forEach(t=>t.stop());clearInterval(timer);btn.textContent='🎙 Record again';const au=btn.parentElement.querySelector('.record-play');au.src=URL.createObjectURL(new Blob(chunks,{type:rec.mimeType}));au.hidden=false};rec.start();start=Date.now();btn.textContent='■ Stop';timer=setInterval(()=>{const s=Math.floor((Date.now()-start)/1000);btn.parentElement.querySelector('.record-time').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`},500)}catch(e){alert('Please allow microphone access to record your answer.')}}})}
function wire(){$$('.exercise').forEach(task=>{restore(task);task.querySelector('.b.check')?.addEventListener('click',()=>check(task));task.querySelector('.b.reset')?.addEventListener('click',()=>reset(task));task.querySelector('.b.answer')?.addEventListener('click',e=>{const a=task.querySelector('.ansbox');if(a.hidden){a.innerHTML=answer(task.dataset.taskId);a.hidden=false;e.currentTarget.textContent='🙈 Hide answer'}else{a.hidden=true;e.currentTarget.textContent='💡 Answer & explanation'}});$$('textarea',task).forEach(t=>t.addEventListener('input',()=>words(t)));record(task)});$$('#content input[type=checkbox]').forEach((x,i)=>{if(x.closest('.exercise'))return;const k=`ielts-hao-home-v7-${lesson}-${major}-${sub||'main'}-${i}`;try{x.checked=localStorage.getItem(k)==='1'}catch(e){};x.onchange=()=>{try{localStorage.setItem(k,x.checked?'1':'0')}catch(e){};progress()}});progress()}
function progress(){let done=0;try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';if(k.startsWith(`ielts-hao-v7-${lesson}-`)&&localStorage.getItem(k))done++}}catch(e){};const pct=Math.min(100,done*4);$('#progressFill').style.width=pct+'%';$('#progressText').textContent=done?`${done} saved responses · ${pct}%`:'0%'}
function boot(){nav();load(lesson);const badge=document.querySelector('.exact');if(badge)badge.innerHTML='<span>⚡</span>Interactive v7<br>prebuilt & stable'}
try{boot()}catch(e){console.error(e);$('#loading').hidden=false;$('#loading').textContent='Could not load Interactive v7: '+e.message;$('#contentShell').hidden=true}
})();
