(function(){
'use strict';
const META={1:['🌱','Baseline & Study System','Lessons 1 & 2'],2:['🗣️','Speaking Baseline & Present Time','Lessons 3 & 4'],3:['⏰','Present Time & Routines','Lessons 5 & 6'],4:['🕰️','Past Time & Experiences','Lessons 7 & 8'],5:['🎉','Special Occasions & Month 1 Check','Lessons 9 & 10'],6:['🚀','Month 1 Consolidation','Lessons 11 & 12']};
const $=s=>document.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’‘]/g,"'").replace(/[^a-z0-9'./-]+/g,' ').trim();
let lesson=+(localStorage.getItem('ielts-hao-lesson')||1),major='overview',sub=null,data=null;
function answerMap(){const old=(window.IELTS_LESSONS||[]).find(x=>x.id===lesson),m={};(old?.tasks||[]).forEach(t=>m[t.id]=t.answer);m['l1-nationalities']='<p><b>1 Japanese · 2 Chinese · 3 Egyptian · 4 Emirati · 5 Portuguese · 6 Malaysian.</b></p>';return m}
function answer(id){return answerMap()[id]||'<p><b>Open response.</b> Compare your work with the task requirements and teacher feedback.</p>'}
function plain(id){const d=document.createElement('div');d.innerHTML=answer(id);return norm(d.textContent)}
function key(el,task){const i=$$('input,textarea,select',task).indexOf(el);return `ielts-hao-v9-${lesson}-${task.dataset.taskId}-${i}`}
function save(el,task){try{localStorage.setItem(key(el,task),el.type==='checkbox'?(el.checked?'1':'0'):el.value)}catch{} progress()}
function words(ta){const n=ta.value.trim()?ta.value.trim().split(/\s+/).length:0,box=ta.parentElement.querySelector('.wordcount');if(box)box.textContent=`${n} word${n===1?'':'s'}`}
function restore(task){$$('input,textarea,select',task).forEach(el=>{try{const v=localStorage.getItem(key(el,task));if(v!==null){if(el.type==='checkbox')el.checked=v==='1';else el.value=v}}catch{};el.addEventListener(el.type==='checkbox'?'change':'input',()=>save(el,task));if(el.tagName==='SELECT')el.addEventListener('change',()=>save(el,task));if(el.tagName==='TEXTAREA')words(el)})}
function nav(){const box=$('#lessonNav');box.innerHTML='';Object.entries(META).forEach(([id,m])=>{const b=document.createElement('button');b.className='lesson-tab'+(+id===lesson?' on':'');b.innerHTML=`<span class="lnum">${id}</span><span><b>${m[0]} ${m[1]}</b><small>${m[2]}</small></span>`;b.onclick=()=>load(+id);box.appendChild(b)})}
function majorTabs(){const box=$('#majorTabs');box.innerHTML='';data.major.forEach(m=>{const b=document.createElement('button');b.className='tab'+(m.id===major?' on':'');b.textContent=m.label;b.onclick=()=>{major=m.id;sub=null;render()};box.appendChild(b)})}
function render(){majorTabs();const m=data.major.find(x=>x.id===major)||data.major[0],sb=$('#subTabs');sb.innerHTML='';let html='';if(m.subtabs?.length){if(!sub||!m.subtabs.some(x=>x.id===sub))sub=m.subtabs[0].id;m.subtabs.forEach(s=>{const b=document.createElement('button');b.className='subtab'+(s.id===sub?' on':'');b.textContent=s.label;b.onclick=()=>{sub=s.id;render()};sb.appendChild(b)});const s=m.subtabs.find(x=>x.id===sub);$('#sectionTitle').textContent=s.title||m.title||m.label;html=s.html||''}else{$('#sectionTitle').textContent=m.title||m.label;html=m.html||''}$('#content').innerHTML=html||'<div class="card">No content in this section.</div>';$('#contentShell').hidden=false;$('#loading').hidden=true;wire();window.scrollTo({top:document.querySelector('main').offsetTop-55,behavior:'smooth'})}
function load(id){lesson=id;major='overview';sub=null;try{localStorage.setItem('ielts-hao-lesson',String(id))}catch{};data=window.IELTS_PRECOMPILED?.[id];nav();const m=META[id];$('#heroIcon').textContent=m[0];$('#heroTitle').textContent=`Lesson ${id} · ${m[1]}`;$('#heroSub').textContent=`Foundation 1 · ${m[2]} · Interactive v9 · full worksheet content rebuilt as direct web practice.`;if(!data){$('#loading').hidden=false;$('#loading').textContent='Interactive lesson data is missing. Please refresh once.';$('#contentShell').hidden=true;return}render();progress()}
function check(task){const a=plain(task.dataset.taskId),score=task.querySelector('.score');let done=0,good=0;$$('.gap',task).forEach(el=>{el.classList.remove('ok','no');const v=norm(el.value);if(!v)return;done++;if(a.includes(v)&&v.length>1){el.classList.add('ok');good++}else el.classList.add('no')});$$('textarea',task).forEach(el=>{if(el.value.trim()){done++;good++}});$$('input[type=checkbox]',task).forEach(el=>{if(el.checked){done++;good++}});if(score)score.textContent=done?`${good}/${done} responses checked`:'Complete the task first.';progress()}
function reset(task){if(!confirm('Reset this task?'))return;$$('input,textarea,select',task).forEach(el=>{try{localStorage.removeItem(key(el,task))}catch{};if(el.type==='checkbox')el.checked=false;else el.value='';el.classList.remove('ok','no')});const a=task.querySelector('.ansbox');if(a)a.hidden=true;const s=task.querySelector('.score');if(s)s.textContent='';$$('textarea',task).forEach(words);progress()}
function recorder(task){$$('.record-btn',task).forEach(btn=>{let rec,chunks=[],timer,start;btn.onclick=async()=>{if(rec?.state==='recording'){rec.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});rec=new MediaRecorder(stream);chunks=[];rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=()=>{stream.getTracks().forEach(t=>t.stop());clearInterval(timer);btn.textContent='🎙 Record again';const audio=btn.parentElement.querySelector('.record-play');audio.src=URL.createObjectURL(new Blob(chunks,{type:rec.mimeType}));audio.hidden=false};rec.start();start=Date.now();btn.textContent='■ Stop';timer=setInterval(()=>{const sec=Math.floor((Date.now()-start)/1000),t=btn.parentElement.querySelector('.record-time');if(t)t.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`},500)}catch{alert('Please allow microphone access to record your answer.')}}})}
function wire(){$$('.exercise').forEach(task=>{restore(task);task.querySelector('.b.check')?.addEventListener('click',()=>check(task));task.querySelector('.b.reset')?.addEventListener('click',()=>reset(task));task.querySelector('.b.answer')?.addEventListener('click',e=>{const a=task.querySelector('.ansbox');if(!a)return;if(a.hidden){a.innerHTML=answer(task.dataset.taskId);a.hidden=false;e.currentTarget.textContent='🙈 Hide answer'}else{a.hidden=true;e.currentTarget.textContent='💡 Answer & explanation'}});$$('textarea',task).forEach(t=>t.addEventListener('input',()=>words(t)));recorder(task)});$$('#content input[type=checkbox]').forEach((x,i)=>{if(x.closest('.exercise'))return;const k=`ielts-hao-home-v9-${lesson}-${major}-${sub||'main'}-${i}`;try{x.checked=localStorage.getItem(k)==='1'}catch{};x.onchange=()=>{try{localStorage.setItem(k,x.checked?'1':'0')}catch{};progress()}});progress()}
function progress(){let filled=0,total=0;data?.major?.forEach(m=>{const html=m.subtabs?.length?m.subtabs.map(s=>s.html||'').join(''):(m.html||'');total+=(html.match(/class=\\?"(?:gap|longanswer)/g)||[]).length});try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i)||'';if(k.startsWith(`ielts-hao-v9-${lesson}-`)&&localStorage.getItem(k))filled++}}catch{};const pct=total?Math.min(100,Math.round(filled/total*100)):0;$('#progressFill').style.width=pct+'%';$('#progressText').textContent=filled?`${filled} saved · ${pct}%`:'0%'}
function boot(){nav();load(lesson)}
try{boot()}catch(e){console.error(e);$('#loading').hidden=false;$('#loading').textContent='Could not load Interactive v9: '+e.message;$('#contentShell').hidden=true}
})();
